language: elixir
elixir:
  - 1.7.3
otp_release:
  - 21.0
env:
  - MIX_ENV=test
# before_script:
  # Set download location
  # - export PLT_FILENAME=elixir-${TRAVIS_ELIXIR_VERSION}_${TRAVIS_OTP_RELEASE}.plt
  # - export PLT_LOCATION=/home/travis/$PLT_FILENAME
  # Download PLT from danielberkompas/travis_elixir_plts on Github
  # Store in $PLT_LOCATION
  # - wget -O $PLT_LOCATION https://raw.github.com/danielberkompas/travis_elixir_plts/master/$PLT_FILENAME
script:
  - mix test --trace
  - MIX_ENV=prod mix do compile --warnings-as-errors, archive.build, archive.install --force
  - mix format --check-formatted
  - mix dialyzer --halt-exit-status
  - mix credo --strict
